### ISSUE TITLE
Files per folder limit doesn't seem to be enforced

### ISSUE THREAD

**Issue by JensRestemeier** [ladyeklipse/ZX-Pokemaster#11]
I am trying to sort the zx archive from archive.org into directories on an SD-Card to make it manageable with [esxdos](https://esxdos.org/index.html):
![image](https://github.com/ladyeklipse/ZX-Pokemaster/assets/2105225/f42f9517-7eac-44cf-ab3e-41025dc0e444)
The files per directory limit doesn't seem to be enforced, it puts everything into huge directories based on the first letter. Or am I using it wrong?
This is both with the installer from sourceforge, and a git checkout from here.

**Comment by ladyeklipse** [comment]
I can't reproduce this so far. Are you sure that there are more than 255 files in at least one directory?
If you are still interested in making this work, please do this:
1. Press "Save Settings...", save your settings file somewhere and upload here.
2. Go to D:/-zx, open command line, type "dir /s /r > list.txt" and upload list.txt here.

**Comment by ladyeklipse** [comment]
Nevermind, I managed to reproduce this with using the exact same path: "D:/-zx". Remove the hyphen from "-zx", make the output folder have only english letters, e. g. "D:/ZX", and it will work fine. I understand that this is not the expected behavior, an unusual case worth looking into, but since there is a workaround, I won't be doing this until the next update.
