### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by ghost** [ladyeklipse/ZX-Pokemaster#3]
1)
If I use a pattern like this (with spaces between each flag) -

{GameName} ({Year}) ({Publisher}) ({MachineType}) {ModFlags}

If there is no ModFlag then it leaves a space at the end of the filename.

2)
Crystal Kingdom Dizzy 2017 is now renamed with the machine type (+2). This could mean 48K or 128K. It should be 128K.

3)
Predator (Activision) is listed as machine type (+2). It should be 48K.

4)
I have about 25 games in my collection that don't have a Machine Type named. List attached. (Compendium by Gremlin is the 128K version) (I could post the actual games but there are a couple of denied ones in their).
[No Machine Type.txt](https://github.com/eklipse2009/ZX-Pokemaster/files/1241920/No.Machine.Type.txt)

**Comment by blinkydoos** [comment]
Regarding the 'Gremlin Compendium' games, WOS and ZXDB are wrong, the game is 48K and 128K. You get AY music in 128K.

**Comment by eklipse2009** [comment]
Thank you very much for your valuable input!
I do have these games, so in this case the names' list is enough.
As for "denied" games - please don't worry, I'm 100% pro-preservation and I strongly believe that we have moral right to distribute abandoned games for the sake of historical preservation.

**Comment by eklipse2009** [comment]
Since ZX Pokemaster is based on ZXDB, changing machine types for ZXDB entries is a point of discussion with Einar Saukas, and we'll sure discuss that.
ZX Spectrum +2 is always a 128K machine, so +2 cannot mean 48K.

**Comment by blinkydoos** [comment]
But a +2 has a selectable 48K mode for tapes so it's not really specifying how much memory is needed to run the game (although 'Crystal Kingdom Dizzy 2017' does give a warning if you try to load it in 48K). Not sure why 'Predator' is named as +2 though because ZXDB has it correctly at 48K,

**Comment by eklipse2009** [comment]
ZX Spectrum +2 has some compatibility issues with the original British ZX Spectrum.
When we select 48K mode in ZX Spectrum +2, it functions in compatibility mode, emulating the behavior of the older model.
+2 and 128K flags are different.
But whether they have been applied correctly or not, is a topic for a debate.
I'll do my best to investigate all the games you've mentioned so that they have correct machine type flag.

**Comment by blinkydoos** [comment]
The poke file for -

Chip Factory - Featuring 'Technician Ted', The (1984) (Hewson Consultants) [48K]

Contains cheats for 48K and 128K but the 128K version is called 'Technician Ted - The Megamix'.

The poke file for 'Technician Ted - The Megamix' contains less cheats and pokes some different addresses.

**Comment by eklipse2009** [comment]
Hi, @blinkydoos ! I did not forget about you and fixed all these minor bugs you mentioned, thanks you for that! We have updated ZXDB as well.
I've done a major update to ZX Pokemaster, but I still call it Beta, because I need someone to test it. 
Could you please test it for me?
https://sourceforge.net/projects/zx-pokemaster/

**Comment by blinkydoos** [comment]
Great work, i'm still a bit dubious about alternate names but I have the option to use my original filenames so thanks. I think a small few Machine Types may be slightly incorrect (some listed as 128K when they can also be loaded in 48K), but that's no big deal. Overall, thanks a lot.

P.S.
I noticed in the R-Type pokes it has these at the end -

NFollowed by and
M 8 34388 0 0
Z 8 34389 91 0

These need some Hex entered before using (according to Tipshop) so they are not useable and just lock up the game.

**Comment by eklipse2009** [comment]
@blinkydoos 
thank you for your reports!
Please don't hesitate to report anything you feel weird about the file sorting.
Keep in mind that you're not just helping me, you're helping the entire ZX Spectrum community, because I'll be releasing a torrent file with all games known to ZX Pokemaster soon ;)
And I've translated all HEXes from that R-Type poke, for now the updated .POK file is just here:
https://github.com/eklipse2009/all-tipshop-pokes/blob/master/r/R-Type%20(1988)(Electric%20Dreams).pok
I've tested this cheat code and it works as described =)
