### ISSUE TITLE
An option to use default title instead of AKA.

### ISSUE THREAD

**Issue by ghost** [ladyeklipse/ZX-Pokemaster#5]
Hi, I wouldn't know where to ask this so i'll just post it here temporarily. Regarding the renaming in the new Tosec dats. I was just watching CLRMame to see what the first few files were being renamed to in the Games TZX dat.

For games that were released in a different country under a different name, shouldn't that name be first in the filename ? For instance -

`Un, Dos, Tres Responda Otra Vez (1984)(CheetahSoft)(16K)[aka 3-2-1][re-release]`

Shouldn't this be named something like -

 `3-2-1 (1984)(CheetahSoft)(16K)[aka Un, Dos, Tres Responda Otra Vez][re-release]`
 
as the publisher is UK and the loading screen also says 3-2-1 ? and the same for the opposite -

`Escape (1982)(Investronica)(16K)(ES)[aka 3D Monstruos][re-release]`

as this is the Spanish version shouldn't it be called -

`3D Monstruos (1982)(Investronica)(16K)(ES)[aka Escape][re-release]`

--------------------------------------------------------------

Also, these three files only contain the 48K version (as the 128K version is on side B which isn't in the TZX) -

Licence to Kill (1989)(Domark)(48K-128K)
Licence to Kill (1989)(Domark)(48K-128K)[a]
Licence to Kill (1989)(Domark)(48K-128K)[a2]

As I said, I only watched the first few being renamed so I just thought i'd say. Thanks for all the hard work by the way. 

(Also, is there a release date for this torrent you spoke of that contains all the games that have a poke file ?)

**Comment by eklipse2009** [comment]
Thanks for these bug reports, I'll certainly investigate and fix those asap!
There is no release date. Maybe today, maybe this weekk, I didn't set myself a deadline.
Currently I've shared a torrent on Facebook (yes, I have balls to share torrents on FB) in my group, it is open:
https://www.facebook.com/groups/zxpokemaster/?ref=bookmarks
It's 6.5Mb, no tracker will accept it and some torrenting software doesn't like it because it has 70000 files.
But I'm releasing a better torrent, with all files neatly packed and some bugs fixed, which will be fixed in TOSEC dats only in the next TOSEC release. I'll share it on thepiratebay and many more places so it should be hard to overlook.

**Comment by ZappaUtopia** [comment]
I just spent 5 minutes trying to find 'Compendium' by Gremlin Graphics, I then found it listed as 'Games Compendium'. The box art, WOS and ZXDB have it listed as 'Compendium'.

There is also 2 other titles listed as 'Games Compendium' and it says (Gremlin Graphics), this should be 'Sinclair Research' -

Games Compendium - Dark Empire + Fantasia Diamond + Hocus Focus + CORE + Peter Shilton's Handball (1987)(Gremlin Graphics)(48K-128K)
Games Compendium - Mummy! Mummy! + Jet Set Gertie + Zoot + Grid Patrol + Xadom + Death Wake (1987)(Gremlin Graphics)(48K-128K)

**Comment by ZappaUtopia** [comment]
Are you going to keep the filenames this way even though other TOSEC sets have them named correctly ? I hope you can change the filenames back to the most common Full Title like it was in previous TOSEC then maybe you could add an option in Pokemaster to use the AKA name instead for those that wan't it ?

**Comment by eklipse2009** [comment]
I'm sorry, I don't like your passive aggressive tone, so I'm closing this issue.
I've taken all your comments into consideration and will do my best to fix the bugs you mentioned, but only when I have time and desire to.
You're still free to use older TOSEC sets, not to use ZX Pokemaster or look through the code, fix the bugs yourself and make a pull request.

**Comment by ZappaUtopia** [comment]
Sorry, I didn't mean it to sound passive aggressive, it was just the way I typed it, I apologise. I only wanted to ask because I didn't know if you read my previous message. Sorry, I only wanted to give feedback on your excellent program. I hope you can re-open this ?

**Comment by eklipse2009** [comment]
Like I said, all your comments will be taken into consideration.
Currently all the names are based on ZXDB and the rule is to take the main title by default and pick one of alternative title if it fully contains the default title. This is what happend to LED Storm.
https://spectrumcomputing.co.uk/index.php?cat=96&id=9369
My policy is this:
1. I notify Einar Saukas about bugs in ZXDB.
2. We discuss bugs and if it is indeed a bug in ZXDB, it is fixed in the next version.
3. In rare cases, I hardcode an exception for some game titles.
I'm well aware about multiple [aka] issue, it is a recurring issue with no easy fix, your note about 'Compendium' is fixed in 1.2-beta3 and the abovementioned bug with LED Storm is ZXDB issue.
If you have other issues, you're free to open another issues or multiple issues, but please do not expect the bugs to be fixed ASAP.

**Comment by ZappaUtopia** [comment]
OK thanks, just out of interest, why do you pick the AKA title ? I thought the Full Title was the most common and the one that appears on the loading screens, inlays etc. otherwise all TOSEC sets would use the AKA ? I don't expect any bugs to be fixed ASAP, I just wanted to report them and make it better whether it's now or next year, just trying to help.

**Comment by eklipse2009** [comment]
I pick AKA title in one and only one case - if it fully contains the original title. From my experience, this is most likely to be the fullest title of the game, as written on advertising or cassette inlay, e. g. Saboteur II - Avenging Angel instead of Saboteur II.
This is a topic of debate, but I had to find at least some general rules, because there's no way I can handle 83000+ files and growing and satisfy the requirements of all users.

**Comment by ZappaUtopia** [comment]
Would it be difficult to add an option in Pokemaster to use the common title instead of the AKA name ? (I'm not expecting you to add it ASAP !).

**Comment by eklipse2009** [comment]
Yes, it is quite possible. I'll reopen this to mark this.

**Comment by ZappaUtopia** [comment]
Just an opinion, please don't take this the wrong way ! I think it would be better to keep the TOSEC names the same as the other system TOSECs (i.e. Default Title). For instance, in the Amstrad, C64, Amiga TOSEC etc. 'Little Computer People' is listed under 'L' but in the Spectrum TOSEC it's listed under 'A' for Activision. Pokemaster could convert the names to the AKA version if need be.

**Comment by eklipse2009** [comment]
TOSEC naming convention implies that the main principle of naming files is correctness, not convenience.
There is a proof that Little Computer People is correctly named The Activision Little Computer People Discovery Kit:
Please see https://spectrumcomputing.co.uk/index.php?cat=96&id=2897
Since you're the second person to bring the issue with this exact game up, I'll take this point and bring up the discussion on that with other members of the TOSEC team.
